name: Build & Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew :publish --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gradle-plugin
          path: ~/.m2/repository/**
          if-no-files-found: error
